---
# tasks file for ospf

  - name: Copy rpm file to servers
    copy:
       src: ./files/frr.rpm
       dest: /home/frr.rpm

  - name: install base tools
    yum:
      state: present
      name:
        - tcpdump
        - net-tools
        - /home/frr.rpm

  - name: Extract file
    fetch:
      src: /etc/frr/daemons
      dest: ./files/daemons
    when: (ansible_hostname == "router1")