---
# tasks file for ospf
- name: install base tools
  yum:
    name:
    - tcpdump
    - net-tools
    - https://github.com/FRRouting/frr/releases/download/frr-5.0.1/frr-5.0.1-2018070501.el7.centos.x86_64.rpm
  state: present