---
# tasks file for ospf

  - name: Copy rpm file to routers
    copy:
       src: ./files/frr.rpm
       dest: /home/frr.rpm

  - name: install base tools
    yum:
      state: present
      name:
        - tcpdump
        - net-tools
        - /home/frr.rpm

  # - name: Extract file
  #   fetch:
  #     src: /etc/frr/daemons
  #     dest: ./files/daemons
  #   when: (ansible_hostname == "router1")

  - name: set up forward packages across routers
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      state: present

  - name: Copy frr.daemons file to routers
    copy:
       src: ./files/daemons
       dest: /etc/frr/daemons
       owner: frr
       group: frr
       mode: 0640

  - name: Copy frr.conf file to router1
    copy:
       src: ./files/frr.conf1.j2
       dest: /etc/frr/frr1.conf
       owner: frr
       group: frr
       mode: 0640
    when: (ansible_hostname == "router1")

  - name: Copy frr.conf file to router2
    copy:
       src: ./files/frr.conf2.j2
       dest: /etc/frr/frr.conf
       owner: frr
       group: frr
       mode: 0640
    when: (ansible_hostname == "router2")

  - name: Copy frr.conf file to router3
    copy:
       src: ./files/frr.conf3.j2
       dest: /etc/frr/frr.conf
       owner: frr
       group: frr
       mode: 0640
    when: (ansible_hostname == "router3")

  - name: restart FRR
    service:
      name: frr
      state: restarted
      enabled: true