---
# tasks file for ospf

  - name: install base tools
    yum:
      state: present
      name:
        - tcpdump
        - net-tools

  # - name: Install frr.rpm
  #   ansible.builtin.yum:
  #     name: https://github.com/FRRouting/frr/releases/download/frr-5.0.1/frr-5.0.1-2018070501.el7.centos.x86_64.rpm
  #     state: present


  - name: Extract file
    fetch:
      src: /etc/frr/daemons
      dest: ./roles/ospf/files/
    when: (ansible_hostname == "router1")

